# Generated by Django 5.2.7 on 2025-10-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100)),
                ('acronym_fac', models.CharField(blank=True, max_length=15, null=True)),
                ('dean_name_fac', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_fac', models.CharField(blank=True, max_length=15, null=True)),
                ('email_fac', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_fac', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('year_fundation_fac', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
