# Generated by Django 5.2.7 on 2025-10-24 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_career', models.CharField(max_length=150)),
                ('directory_car', models.CharField(blank=True, max_length=15, null=True)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('phone_car', models.CharField(blank=True, max_length=15, null=True)),
                ('email_car', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.facultys')),
            ],
        ),
    ]
