# Generated by Django 5.2.7 on 2025-10-24 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=160, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('pdf', models.FileField(blank=True, upload_to='pdfs')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Career.careers')),
            ],
        ),
    ]
